### ISSUE TITLE
Maven update - update repository to resolve the errors (for some of the jars).

### ISSUE THREAD

**Issue by n10n** [synereo/dockernode#3]
=============================================== java-cup-11a-runtime-local.jar, JLex-local-local.jar, prolog4j-api-0.2.1-SNAPSHOT.jar and configgy-local.jar.

Downloading: http://repository.codehaus.org/com/thoughtworks/org/prolog4j/prolog4j-api/0.2.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.prolog4j:prolog4j-api:0.2.1-SNAPSHOT/maven-metadata.xml from/to repository.codehaus.org (http://repository.codehaus.org/com/thoughtworks): repository.codehaus.org: unknown error
[WARNING] Failure to transfer org.prolog4j:prolog4j-api:0.2.1-SNAPSHOT/maven-metadata.xml from http://repository.codehaus.org/com/thoughtworks was cached in the local repository, resolution will not be reattempted until the update interval of repository.codehaus.org has elapsed or updates are forced. Original error: Could not transfer metadata org.prolog4j:prolog4j-api:0.2.1-SNAPSHOT/maven-metadata.xml from/to repository.codehaus.org (http://repository.codehaus.org/com/thoughtworks): repository.codehaus.org: unknown error
Downloading: http://repository.codehaus.org/com/thoughtworks/org/prolog4j/prolog4j-api/0.2.1-SNAPSHOT/prolog4j-api-0.2.1-SNAPSHOT.pom
Downloading: http://repository.codehaus.org/com/thoughtworks/org/prolog4j/prolog4j-tuprolog/0.2.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.prolog4j:prolog4j-tuprolog:0.2.1-SNAPSHOT/maven-metadata.xml from/to repository.codehaus.org (http://repository.codehaus.org/com/thoughtworks): repository.codehaus.org
[WARNING] Failure to transfer org.prolog4j:prolog4j-tuprolog:0.2.1-SNAPSHOT/maven-metadata.xml from http://repository.codehaus.org/com/thoughtworks was cached in the local repository, resolution will not be reattempted until the update interval of repository.codehaus.org has elapsed or updates are forced. Original error: Could not transfer metadata org.prolog4j:prolog4j-tuprolog:0.2.1-SNAPSHOT/maven-metadata.xml from/to repository.codehaus.org (http://repository.codehaus.org/com/thoughtworks): repository.codehaus.org
Downloading: http://repository.codehaus.org/com/thoughtworks/org/prolog4j/prolog4j-tuprolog/0.2.1-SNAPSHOT/prolog4j-tuprolog-0.2.1-SNAPSHOT.pom
Downloading: http://repository.codehaus.org/com/thoughtworks/jlex/JLex-local/local/JLex-local-local.pom
Downloading: http://repository.codehaus.org/com/thoughtworks/cup/java-cup-11a/local/java-cup-11a-local.pom
Downloading: http://repository.codehaus.org/com/thoughtworks/cup/java-cup-11a-runtime/local/java-cup-11a-runtime-local.pom
Downloading: http://repository.codehaus.org/com/thoughtworks/net/lag/configgy/local/configgy-local.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.742 s
[INFO] Finished at: 2016-05-12T01:00:03+00:00
[INFO] Final Memory: 9M/31M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project specialK: Could not resolve dependencies for project com.biosimilarity.lift:specialK:jar:1.1.8.5: Failed to collect dependencies at org.prolog4j:prolog4j-api:jar:0.2.1-SNAPSHOT: Failed to read artifact descriptor for org.prolog4j:prolog4j-api:jar:0.2.1-SNAPSHOT: Could not transfer artifact org.prolog4j:prolog4j-api:pom:0.2.1-SNAPSHOT from/to repository.codehaus.org (http://repository.codehaus.org/com/thoughtworks): repository.codehaus.org: Unknown host repository.codehaus.org -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project specialK: Could not resolve dependencies for project com.biosimilarity.lift:specialK:jar:1.1.8.5: Failed to collect dependencies at org.prolog4j:prolog4j-api:jar:0.2.1-SNAPSHOT
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.biosimilarity.lift:specialK:jar:1.1.8.5: Failed to collect dependencies at org.prolog4j:prolog4j-api:jar:0.2.1-SNAPSHOT
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
    ... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.prolog4j:prolog4j-api:jar:0.2.1-SNAPSHOT
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
    ... 24 more

=============================================== scala-pickling_2.10-0.8.0-Local.jar,

Downloaded: https://repo.maven.apache.org/maven2/junit/junit/4.8.1/junit-4.8.1.pom (949 B at 14.9 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.289 s
[INFO] Finished at: 2016-05-12T05:34:38+00:00
[INFO] Final Memory: 11M/31M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project agentservices-store-ia: Could not resolve dependencies for project com.protegra-ati:agentservices-store-ia:jar:1.9.5: Failed to collect dependencies at org.scala-lang:scala-pickling_2.10:jar:0.8.0-Local: Failed to read artifact descriptor for org.scala-lang:scala-pickling_2.10:jar:0.8.0-Local: Could not transfer artifact org.scala-lang:scala-pickling_2.10:pom:0.8.0-Local from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Access denied to: https://oss.sonatype.org/content/groups/scala-tools/org/scala-lang/scala-pickling_2.10/0.8.0-Local/scala-pickling_2.10-0.8.0-Local.pom , ReasonPhrase:Forbidden. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project agentservices-store-ia: Could not resolve dependencies for project com.protegra-ati:agentservices-store-ia:jar:1.9.5: Failed to collect dependencies at org.scala-lang:scala-pickling_2.10:jar:0.8.0-Local
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.protegra-ati:agentservices-store-ia:jar:1.9.5: Failed to collect dependencies at org.scala-lang:scala-pickling_2.10:jar:0.8.0-Local
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
    ... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.scala-lang:scala-pickling_2.10:jar:0.8.0-Local
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
    ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.scala-lang:scala-pickling_2.10:jar:0.8.0-Local
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
    ... 26 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.scala-lang:scala-pickling_2.10:pom:0.8.0-Local from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Access denied to: https://oss.sonatype.org/content/groups/scala-tools/org/scala-lang/scala-pickling_2.10/0.8.0-Local/scala-pickling_2.10-0.8.0-Local.pom , ReasonPhrase:Forbidden.
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
    ... 33 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.scala-lang:scala-pickling_2.10:pom:0.8.0-Local from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Access denied to: https://oss.sonatype.org/content/groups/scala-tools/org/scala-lang/scala-pickling_2.10/0.8.0-Local/scala-pickling_2.10-0.8.0-Local.pom , ReasonPhrase:Forbidden.
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 36 more
Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Access denied to: https://oss.sonatype.org/content/groups/scala-tools/org/scala-lang/scala-pickling_2.10/0.8.0-Local/scala-pickling_2.10-0.8.0-Local.pom , ReasonPhrase:Forbidden.
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1001)
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
    at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
    at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
    at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
    at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
    at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
    at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
    ... 41 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[INFO] Build failures were ignored.

**Comment by n10n** [comment]
As a temporary fix added five jar files to Docker creation process rather then using Maven for now but need to find the appropriate fix.
